import { FiBell, FiCheckCircle } from "react-icons/fi";
import { useAuth } from "../../features/auth";

const Header = () => {
    const { usuario } = useAuth();

    return (
        <header
            className="
                sticky
                top-0
                z-30
                flex
                h-24
                items-center
                justify-between
                border-b
                border-gray-200
                bg-white/95
                px-10
                backdrop-blur-md
            "
        >
            {/* IZQUIERDA */}
            <div>
                <h1
                    className="
                        text-3xl
                        font-bold
                        tracking-tight
                        text-primary
                    "
                >
                    Dashboard
                </h1>
                <p
                    className="
                        mt-1
                        text-sm
                        text-gray-500
                    "
                >
                    Bienvenido nuevamente
                    <span
                        className="
                            ml-1
                            font-bold
                            text-primary
                        "
                    >
                        {usuario?.nombre}
                    </span>
                </p>
            </div>

            {/* DERECHA */}
            <div
                className="
                    flex
                    items-center
                    gap-6
                "
            >
                {/* Estado del sistema */}
                <div
                    className="
                        flex
                        items-center
                        gap-3
                        rounded-2xl
                        border
                        border-gray-100
                        bg-white
                        px-5
                        py-3
                        shadow-sm
                    "
                >
                    {/* Indicador visual */}
                    <div
                        className="
                            flex
                            h-9
                            w-9
                            items-center
                            justify-center
                            rounded-full
                            bg-accent/20
                        "
                    >
                        <FiCheckCircle
                            size={20}
                            className="text-accent"
                        />
                    </div>
                    {/* Información del estado */}
                    <div>
                        <p
                            className="
                                text-xs
                                font-medium
                                text-gray-500
                            "
                        >
                            Estado del sistema
                        </p>
                        <div
                            className="
                                mt-0.5
                                flex
                                items-center
                                gap-2
                            "
                        >
                            <span
                                className="
                                    h-2
                                    w-2
                                    rounded-full
                                    bg-accent
                                "
                            />
                            <span
                                className="
                                    text-sm
                                    font-bold
                                    text-primary
                                "
                            >
                                Operativo
                            </span>
                        </div>
                    </div>
                </div>

                {/* Notificaciones */}
                <button
                    className="
                        relative
                        flex
                        h-11
                        w-11
                        items-center
                        justify-center
                        rounded-full
                        border
                        border-gray-100
                        bg-white
                        shadow-sm
                        transition-all
                        duration-200
                        hover:bg-gray-50
                        active:scale-95
                    "
                >
                    <FiBell
                        size={20}
                        className="text-primary"
                    />
                    <span
                        className="
                            absolute
                            right-2.5
                            top-2.5
                            h-2
                            w-2
                            rounded-full
                            bg-red-500
                        "
                    />
                </button>

                {/* Usuario */}
                <div
                    className="
                        flex
                        items-center
                        gap-4
                        rounded-2xl
                        border
                        border-gray-100
                        bg-white
                        px-4
                        py-2
                        shadow-sm
                    "
                >
                    <div
                        className="
                            flex
                            h-11
                            w-11
                            items-center
                            justify-center
                            rounded-full
                            bg-primary/10
                            text-lg
                            font-bold
                            text-primary
                        "
                    >
                        {usuario?.nombre?.charAt(0).toUpperCase()}
                    </div>
                    <div>
                        <p
                            className="
                                text-sm
                                font-bold
                                text-primary
                            "
                        >
                            {usuario?.nombre}
                        </p>
                        <span
                            className="
                                mt-0.5
                                inline-flex
                                rounded-full
                                bg-primary/10
                                px-2.5
                                py-0.5
                                text-xs
                                font-bold
                                text-primary
                            "
                        >
                            {usuario?.rol}
                        </span>
                    </div>
                </div>
            </div>
        </header>
    );
};

export default Header;